package ar.com.phidalgo.ciudadanias.europeas.gui;

import ar.com.phidalgo.ciudadanias.europeas.gui.transactional.GestionTiposTramite;

/**
 * @author phidalgo
 */
public class MenuTiposTramite extends javax.swing.JFrame {

    /**
     * Creates new form GestionTramite
     */
    public MenuTiposTramite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNuevoTipoTramite = new javax.swing.JButton();
        jButtonBajaTipoTramite = new javax.swing.JButton();
        jButtonConsultaTipoTramite = new javax.swing.JButton();
        jButtonConsultarTodos = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonModificarTipoTramite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipos Trámite");

        jButtonNuevoTipoTramite.setText("Nuevo Tipo Trámite");
        jButtonNuevoTipoTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoTipoTramiteActionPerformed(evt);
            }
        });

        jButtonBajaTipoTramite.setText("Baja Tipo Trámite");
        jButtonBajaTipoTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaTipoTramiteActionPerformed(evt);
            }
        });

        jButtonConsultaTipoTramite.setText("Consulta Tipo Trámite");
        jButtonConsultaTipoTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaTipoTramiteActionPerformed(evt);
            }
        });

        jButtonConsultarTodos.setText("Consultar Todos");
        jButtonConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodosActionPerformed(evt);
            }
        });

        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonModificarTipoTramite.setText("Modificar Tipo Trámite");
        jButtonModificarTipoTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTipoTramiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModificarTipoTramite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBajaTipoTramite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultaTipoTramite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNuevoTipoTramite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNuevoTipoTramite)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultaTipoTramite)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarTodos)
                .addGap(18, 18, 18)
                .addComponent(jButtonBajaTipoTramite)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarTipoTramite)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBajaTipoTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaTipoTramiteActionPerformed
        
    }//GEN-LAST:event_jButtonBajaTipoTramiteActionPerformed

    private void jButtonConsultaTipoTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaTipoTramiteActionPerformed
        this.setVisible(false);
        this.dispose();
        GestionTiposTramite gestionTiposTramite = new GestionTiposTramite();
        gestionTiposTramite.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaTipoTramiteActionPerformed

    private void jButtonConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodosActionPerformed
        // TODO add your handling code here:
        // Ir a la lista...
    }//GEN-LAST:event_jButtonConsultarTodosActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
        this.dispose();
        MenuInicial menuInicial = new MenuInicial();
        menuInicial.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModificarTipoTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTipoTramiteActionPerformed
        this.setVisible(false);
        this.dispose();
        GestionTiposTramite gestionTiposTramite = new GestionTiposTramite();
        gestionTiposTramite.setVisible(true);
    }//GEN-LAST:event_jButtonModificarTipoTramiteActionPerformed

    private void jButtonNuevoTipoTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoTipoTramiteActionPerformed
        this.setVisible(false);
        this.dispose();
        GestionTiposTramite gestionTiposTramite = new GestionTiposTramite();
        gestionTiposTramite.setVisible(true);
    }//GEN-LAST:event_jButtonNuevoTipoTramiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTiposTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTiposTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTiposTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTiposTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTiposTramite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBajaTipoTramite;
    private javax.swing.JButton jButtonConsultaTipoTramite;
    private javax.swing.JButton jButtonConsultarTodos;
    private javax.swing.JButton jButtonModificarTipoTramite;
    private javax.swing.JButton jButtonNuevoTipoTramite;
    private javax.swing.JButton jButtonVolver;
    // End of variables declaration//GEN-END:variables
}