package ar.com.phidalgo.ciudadanias.europeas.gui;

import ar.com.phidalgo.ciudadanias.europeas.gui.MenuInicial;

/**
 * @author phidalgo
 */
public class MenuRoles extends javax.swing.JFrame {

    /**
     * Creates new form GestionTramite
     */
    public MenuRoles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNuevRol = new javax.swing.JButton();
        jButtonBajaRol = new javax.swing.JButton();
        jButtonconsultaRol = new javax.swing.JButton();
        jButtonConsultaTodos = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonModificarRol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roles");

        jButtonNuevRol.setText("Nuevo Rol");
        jButtonNuevRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevRolActionPerformed(evt);
            }
        });

        jButtonBajaRol.setText("Baja Rol");
        jButtonBajaRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaRolActionPerformed(evt);
            }
        });

        jButtonconsultaRol.setText("Consulta Rol");
        jButtonconsultaRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultaRolActionPerformed(evt);
            }
        });

        jButtonConsultaTodos.setText("Consultar Todos");
        jButtonConsultaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaTodosActionPerformed(evt);
            }
        });

        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonModificarRol.setText("Modificar Rol");
        jButtonModificarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonModificarRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonNuevRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonconsultaRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultaTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBajaRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNuevRol)
                .addGap(18, 18, 18)
                .addComponent(jButtonconsultaRol)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultaTodos)
                .addGap(18, 18, 18)
                .addComponent(jButtonBajaRol)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarRol)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBajaRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBajaRolActionPerformed

    private void jButtonconsultaRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultaRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonconsultaRolActionPerformed

    private void jButtonConsultaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultaTodosActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.dispose();
        MenuInicial menuInicial = new MenuInicial();
        menuInicial.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModificarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarRolActionPerformed

    private void jButtonNuevRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRoles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBajaRol;
    private javax.swing.JButton jButtonConsultaTodos;
    private javax.swing.JButton jButtonModificarRol;
    private javax.swing.JButton jButtonNuevRol;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JButton jButtonconsultaRol;
    // End of variables declaration//GEN-END:variables
}
